version: '3'
services:
  # フロントエンド (live-trancer)
  live-trancer:
    build: ./live-trancer
    image: 145023112867.dkr.ecr.ap-northeast-1.amazonaws.com/live-trancer:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm start
    depends_on:
      - summary
      - transcription
      - audio-processing

  # バックエンド (audio-processing service)
  audio-processing:
    build: ./microservices/services/audio-processing
    # image: 145023112867.dkr.ecr.ap-northeast-1.amazonaws.com/audio-processing:latest
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
    command: npm start

  # バックエンド (transcription service)
  summary:
    build: ./microservices/services/summary
    # image: 145023112867.dkr.ecr.ap-northeast-1.amazonaws.com/transcription:latest
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
    command: npm start

  # バックエンド (transcription service)
  transcription:
    build: ./microservices/services/transcription
    # image: 145023112867.dkr.ecr.ap-northeast-1.amazonaws.com/transcription:latest
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    command: npm start
